export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Security',
    headline: 'Store, Encrypt, and Retrieve',
    description: 'Store all of your passwords at one place and never forget the password to any of your accounts again!',
    buttonLabel: 'About Us',
    buttonPath: '/AboutUs',
    imgStart: false,
    img: require('../../images/pass_secure.svg'),
    alt: 'passwordSecure',
    dark: true,
    primary: true,
    darkText: false
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Manage all of your saved data',
    description: 'Utilize our encryption processes to further secure your usernames and passwords',
    buttonLabel: 'Learn More',
    buttonPath: '/Discover',
    imgStart: true,
    img: require('../../images/safe.svg'),
    alt: 'pass_secure',
    dark: false,
    primary: false,
    darkText: true
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Register Now',
    headline: 'Create an account with us',
    description: 'Store all of your passwords at one place and never forget the password to any of your accounts again!',
    buttonLabel: 'Sign Up',
    buttonPath: '/signup',
    imgStart: false,
    img: require('../../images/login.svg'),
    alt: 'Login',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjFour = {
    id: 'logger',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Register Now',
    headline: 'Create an account with us',
    description: 'Store all of your passwords at one place and never forget the password to any of your accounts again!',
    buttonLabel: 'Sign Up',
    buttonPath: '/signup',
    imgStart: false,
    img: require('../../images/login.svg'),
    alt: 'Login',
    dark: true,
    primary: true,
    darkText: false,
};